1 Импорт библиотеки numpy

In [2]:
import numpy as np

2 Примеры создания массивов

In [14]:
#Создание массиа из обычного списка
m1 = np.array([0, 1, 2, 3, 4, 5])
display(m1)

#Создание массива с использованием функций zeros, ones, arange
m2 = np.zeros(6)   #создание массива нулей
m3 = np.ones(6)    #создание массива едениц
m4 = np.arange(6)  #создание массива с диапозоном значений
display(m2, m3, m4)

array([0, 1, 2, 3, 4, 5])

array([0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1.])

array([0, 1, 2, 3, 4, 5])

3 Демонстрация атрибутов 

In [26]:
m5 = np.arange(6).reshape(2, 3)
display(m5)
display(m5.shape)  #показывает размерность массива
display(m5.dtype)  #выводит информацию о типах данных массива

array([[0, 1, 2],
       [3, 4, 5]])

(2, 3)

dtype('int64')

4 Примеры индексирования и срезов 

In [33]:
x = m5[0,2]          #выборка конкретного элемента по индексу
display(x) 
srez = m5[1, 0:3]    #пример среза, а конкретней 2я строка и элементы с 0 по 2 включительно массва m5 
display(srez)

np.int64(2)

array([3, 4, 5])

5 Примеры векторных операций и базовых статистик

In [41]:
# Векторные операции и статистика
m6 = np.arange(0, 3)
m7 = np.arange(3, 6)
display(m6, m7)

# Поэлементные операции
m_s = m6 + m7
display(m_s)        #Поэлементная сумма
m_m = m6 * m7
print(m_m)          #Поэлементное произведение

# Базовая статистика
m_mean = m7.mean()
print(m_mean)       #Среднее значение массива m7

m_std = m6.std()
print(m_std)   #Стандартное отклонение массива m6

array([0, 1, 2])

array([3, 4, 5])

array([3, 5, 7])

[ 0  4 10]
4.0
0.816496580927726
